/**
 * Catálogo de textos do PedidoAI.
 *
 * Cada chave é `<tela>.<elemento>`, e o valor é o texto que aparece hoje —
 * byte a byte. Esta etapa é refactor puro: nada muda na tela.
 *
 * Marcadores `{nome}` são substituídos por `interpolar()`. Um texto com valor
 * no meio ("3 itens") vira "{n} itens" — sem isso, a extração começaria
 * quebrando o que funciona.
 *
 * LIMITES declara o comprimento máximo de uma chave cujo layout é apertado.
 * Serve ao Sprint 3c: um texto gerado por IA que estoure o limite destrói a
 * tela que os Sprints 1 e 2 calibraram. Chave sem limite é livre.
 */

export const COPY_PADRAO = {
    "login.bemvindo":              "Bem-vindo",
    "login.titulo":                "Faça seu pedido agora.",
    "login.subtitulo":             "Digite seu telefone para começar. Tudo rapidinho, sem cadastro chato.",
    "login.telefone":              "Telefone",
    "login.placeholder_telefone":  "(11) 99999-9999",
    "login.continuar":             "Continuar",
    "login.termos":                "Ao continuar, você concorda com receber pedidos via WhatsApp.",
    "login.que_bom_te_ver":        "Que bom te ver",
    "login.pronto":                "Pronto pra montar mais um pedido?",
    "login.entrar_pedir":          "Entrar e pedir",
    "login.nao_sou_eu":            "Não sou eu",
    "login.primeiro_acesso":       "Primeiro acesso",
    "login.dados_rapidos":         "Só uns dados rápidos para conseguirmos entregar direitinho na sua casa.",
    "login.nome_completo":         "Nome completo",
    "login.como_posso_chamar":     "Como posso te chamar?",
    "login.cep_nao_encontrado":    "CEP não encontrado.",
    "login.placeholder_cep":       "00000-000",
    "login.endereco":              "Endereço",
    "login.numero":                "Número",
    "login.placeholder_numero":    "123",
    "login.entrega_gratis":        "Entrega grátis",
    "login.cadastrar_entrar":      "Cadastrar e entrar",
    "login.voltar":                "Voltar",
    "login.precisa_loja":          "Não sabemos de qual loja você veio. Abra o link que a loja te enviou para continuar.",
    "login.loja_aberta":           "Loja Aberta",
    "login.erro_entrar":           "Erro ao entrar. Tente novamente.",
    "login.erro_cadastrar":        "Erro ao cadastrar. Tente novamente.",

    "cabecalho.buscar":            "Buscar materiais…",
    "cabecalho.buscar_rotulo":     "Buscar",
    "cabecalho.sair":              "Sair",
    "cabecalho.catalogo":          "Catálogo",
    "cabecalho.meus_pedidos":      "Meus Pedidos",

    "catalogo.categorias":         "Categorias",
    "catalogo.finalizar":          "Finalizar",

    "perfil.sua_conta":            "Sua conta",
    "perfil.meu_perfil":           "Meu perfil",
    "perfil.meus_pedidos":         "Meus pedidos",
    "perfil.endereços":            "Endereços",
    "perfil.pedidos_rótulo":       "Pedidos",
    "perfil.membro_rótulo":        "Membro",
    "perfil.sair_da_conta":        "Sair da conta",
    "perfil.identidade":           "Identidade",
    "perfil.telefone":             "Telefone",
    "perfil.endereço":             "Endereço",
    "perfil.não_informado":        "Não informado",
    "perfil.total_de_pedidos":     "Total de pedidos",
    "perfil.membro_desde":         "Membro desde",
    "perfil.histórico":            "Histórico",
    "perfil.locais_salvos":        "Locais salvos",
    "perfil.trabalho":             "Trabalho",
    "perfil.adicionar_endereço_trabalho": "Adicionar endereço de trabalho",
    "perfil.preferências":         "Preferências",
    "perfil.notificações":         "Notificações",
    "perfil.receber_atualizações": "Receber atualizações de pedido",
    "perfil.modo_escuro":          "Modo escuro",
    "perfil.conta":                "Conta",
    "perfil.nome_completo":        "Nome completo",
    "perfil.endereço_principal":   "Endereço principal",
    "perfil.placeholder_nome":     "João Silva",
    "perfil.endereço_label":       "Endereço",
    "perfil.salvando":             "Salvando...",
    "perfil.seus_pedidos_recentes": "Seus pedidos recentes",
    "perfil.meus_pedidos_section": "Meus pedidos",
    "perfil.endereços_section":    "Endereços",
    "perfil.principal":            "Principal",
    "perfil.ajustes_rápidos":      "Ajustes rápidos",
    "perfil.em_breve":             "em breve",
    "perfil.informações_pessoais": "Informações pessoais",
    "perfil.dados_atualizados":    "Dados atualizados com sucesso.",
    "perfil.nome_completo_asterisco": "Nome completo *",
    "perfil.telefone_asterisco":   "Telefone *",
    "perfil.novo_cep":             "Novo CEP",
    "perfil.cep_opcional":         "(opcional — deixe em branco para manter o endereço atual)",
    "perfil.placeholder_cep":      "00000-000",
    "perfil.número":               "Número",
    "perfil.placeholder_número":   "123",
    "perfil.cancelar":             "Cancelar",
    "perfil.salvar_alterações":    "Salvar alterações",
    "perfil.placeholder_telefone": "(11) 99999-0001",

    "checkout.breadcrumb":         "breadcrumb",
    "checkout.checkout_titulo":    "Checkout",
    "checkout.última_etapa":       "Última etapa",
    "checkout.carrinho":           "Carrinho",
    "checkout.carrinho_vazio":     "Carrinho vazio.",
    "checkout.remover":            "Remover",
    "checkout.entrega_label":      "Entrega",
    "checkout.entrega_disponível": "Entrega disponível",
    "checkout.fora_da_área":       "Fora da área.",
    "checkout.endereço_label":     "Endereço",
    "checkout.opcional":           "(opcional)",
    "checkout.placeholder_complemento": "Apto, bloco, ref.",
    "checkout.pagamento":          "Pagamento",
    "checkout.resumo":             "Resumo",
    "checkout.seu_pedido":         "Seu pedido",
    "checkout.subtotal":           "Subtotal",
    "checkout.fora_da_área_simple": "Fora da área",
    "checkout.a_calcular":         "A calcular",
    "checkout.total":              "Total",
    "checkout.termos_de_serviço":  "Termos de Serviço",
    "checkout.cupom":              "Cupom",
    "checkout.desconto":           "desconto?",
    "checkout.placeholder_cupom":  "CÓDIGO",
    "checkout.endereço_de_entrega": "Endereço de entrega",
    "checkout.alterar":            "Alterar",
    "checkout.cep":                "CEP",
    "checkout.número":             "Número",
    "checkout.complemento":        "Complemento",
    "checkout.como_prefere_pagar": "Como prefere pagar?",
    "checkout.qr_code_pix":        "O QR Code do PIX será gerado quando você finalizar o pedido.",
    "checkout.finalizar_pedido":   "Finalizar pedido",
    "checkout.ao_finalizar":       "Ao finalizar, você concorda com os",
    "checkout.tem_um":             "Tem um",
    "checkout.aplicar":            "Aplicar",

    "pedido.não_encontrado":       "Pedido não encontrado",
    "pedido.cancelado":            "Este pedido foi cancelado.",
    "pedido.sucesso":              "SUCESSO",
    "pedido.cancelado_label":      "Pedido cancelado",
    "pedido.status_envio":         "Status do Envio",
    "pedido.a_caminho":            "A caminho",
    "pedido.resumo":               "Resumo do Pedido",
    "pedido.subtotal":             "Subtotal",
    "pedido.taxa_entrega":         "Taxa de entrega",
    "pedido.a_calcular":           "A calcular",
    "pedido.total":                "Total",
    "pedido.cliente":              "CLIENTE",
    "pedido.pedido_feito_em":      "PEDIDO FEITO EM",
    "pedido.tem_certeza":          "Tem certeza?",
    "pedido.ação_não_desfeita":    "Esta ação não pode ser desfeita.",
    "pedido.fazer_novo":           "Fazer novo pedido",
    "pedido.cancelar_pedido":      "Cancelar pedido",
    "pedido.manter":               "Manter",
    "pedido.sim_cancelar":         "Sim, cancelar",
    "pedido.ver_recibo":           "Ver Recibo",
    "pedido.novo_pedido":          "Novo Pedido",
} as const;

export type CopyKey = keyof typeof COPY_PADRAO;

/** Comprimento máximo por chave, onde o layout não perdoa. */
export const LIMITES: Partial<Record<CopyKey, number>> = {
    "login.bemvindo":              20,
    "login.titulo":                48,
    "login.continuar":             20,
    "login.que_bom_te_ver":        20,
    "login.placeholder_telefone":  16,
    "login.nao_sou_eu":            18,
    "login.primeiro_acesso":       20,
    "login.entrega_gratis":        18,
    "login.placeholder_numero":    8,
    // Os dois CTAs dividem a linha do botão com uma seta de 16px e não quebram
    // em duas linhas: texto longo aqui estoura o botão em vez de embrulhar.
    "login.entrar_pedir":          24,
    "login.cadastrar_entrar":      24,
    "login.voltar":                16,
    // Itens de menu no cabeçalho: cabem lado a lado numa barra estreita.
    "cabecalho.catalogo":          18,
    "cabecalho.meus_pedidos":      18,
    "catalogo.finalizar":          16,
    // Navegação lateral em mobile/tablets
    "perfil.sair_da_conta":        18,
    // Configurações
    "perfil.modo_escuro":          18,
    // Botão de ação
    "perfil.salvando":             16,
};
