-- Expand orders.status to allow 'cancelado'.
--
-- Migration 001 added an inline CHECK constraint whose name was
-- auto-generated by Postgres (commonly 'orders_status_check' but not
-- guaranteed). This block finds and drops every CHECK constraint on the
-- orders table, then adds the correct one with a known name.

DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = 'orders'::regclass
          AND contype = 'c'
    LOOP
        EXECUTE format('ALTER TABLE orders DROP CONSTRAINT %I', r.conname);
    END LOOP;
END $$;

ALTER TABLE orders
    ADD CONSTRAINT orders_status_check
    CHECK (status IN ('novo', 'confirmado', 'rota', 'entregue', 'cancelado'));
